#!/usr/bin/env bash

set -e

DOTFILES=${DOTFILES:-"$HOME/.dotfiles"}

# shellcheck source=../.utils/functions.sh
source "${DOTFILES}/.utils/functions.sh"

echo -e "${c_purple}
 __         ______            _____     ______     ______   ______   __     __         ______     ______
/\ \       /\  ___\    ____  /\  __-.  /\  __ \   /\__  _\ /\  ___\ /\ \   /\ \       /\  ___\   /\  ___\\
\ \ \____  \ \ \____  /\___\ \ \ \/\ \ \ \ \/\ \  \/_/\ \/ \ \  __\ \ \ \  \ \ \____  \ \  __\   \ \___  \\
 \ \_____\  \ \_____\ \/___/  \ \____-  \ \_____\    \ \_\  \ \_\    \ \_\  \ \_____\  \ \_____\  \/\_____\\
  \/_____/   \/_____/          \/____/   \/_____/     \/_/   \/_/     \/_/   \/_____/   \/_____/   \/_____/

Bootstrapping . . .${c_reset}
"



self_update
load_dotfiles_env_filegs
force_sudo
update_system
do_all_install
