#!/usr/bin/env bash

set -e

DOTFILES=${DOTFILES:-"$HOME/.dotfiles"}

# shellcheck source=../.utils/functions.sh
source "${DOTFILES}/.utils/functions.sh"

echo -e "${c_green}
 __         ______            _____     ______     ______   ______   __     __         ______     ______
/\ \       /\  ___\    ____  /\  __-.  /\  __ \   /\__  _\ /\  ___\ /\ \   /\ \       /\  ___\   /\  ___\\
\ \ \____  \ \ \____  /\___\ \ \ \/\ \ \ \ \/\ \  \/_/\ \/ \ \  __\ \ \ \  \ \ \____  \ \  __\   \ \___  \\
 \ \_____\  \ \_____\ \/___/  \ \____-  \ \_____\    \ \_\  \ \_\    \ \_\  \ \_____\  \ \_____\  \/\_____\\
  \/_____/   \/_____/          \/____/   \/_____/     \/_/   \/_/     \/_/   \/_____/   \/_____/   \/_____/

Bootstrapping . . .${c_reset}
"

# shellcheck source=../.utils/tests.sh
source "${DOTFILES}/.utils/tests.sh"
