#!/usr/bin/env bash

CFLAGS="-I$(brew86 --prefix openssl@1.1)/include -I$(brew86 --prefix zlib) -I$(brew86 --prefix readline)/include" \
LDFLAGS="-L$(brew86 --prefix openssl@1.1)/lib -L$(brew86 --prefix readline)/lib" \
VERSION_ALIAS="3.8.14_x86" \
pyenv86 install -v 3.8.14